name: Publish to Github Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Publish to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.2
        with:
          source-directory: website
